[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[full]>=0.117.1",
    "uagents>=0.22.9",
    "uvicorn>=0.37.0",
]
